from typing import List
from pydantic import BaseModel, field_validator


class EmbeddingVector(BaseModel):
    """
    Numerical representation of text content generated by Cohere models; used for semantic similarity search
    """
    vector_id: str  # Unique identifier for this vector in Qdrant
    document_chunk_id: str  # Reference to the source document chunk
    values: List[float]  # The actual embedding vector values
    model_name: str  # Name of the model used to generate this embedding
    dimension: int  # Number of dimensions in the embedding vector

    @field_validator('values')
    def validate_embedding_values(cls, v):
        # For Cohere embeddings, typical dimension is 1024, but we'll allow flexibility
        # The exact dimension will be validated based on the model used
        if not v or len(v) == 0:
            raise ValueError('values must not be empty')
        return v

    @field_validator('model_name')
    def validate_model_name(cls, v):
        # Validate that model name matches expected Cohere model identifier
        if not v or v.strip() == "":
            raise ValueError('model_name must not be empty')
        return v

    @field_validator('dimension')
    def validate_dimension(cls, v):
        if v <= 0:
            raise ValueError('dimension must be positive')
        return v