import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',

    {
      type: 'category',
      label: '001-chapter-1-physical-ai-humanoid-robotics-intro',
      collapsed: true, // dropdown opened by default
      items: [
        'chapter-1-physical-ai-humanoid-robotics-intro/part1',
        'chapter-1-physical-ai-humanoid-robotics-intro/part2',
        'chapter-1-physical-ai-humanoid-robotics-intro/part3',
      ],
    },

    {
      type: 'category',
      label: '002-chapter-2-embodied-intelligence',
      collapsed: true, // dropdown opened by default
      items: [
        'chapter-2-embodied-intelligence/part1',
        'chapter-2-embodied-intelligence/part2',
        'chapter-2-embodied-intelligence/part3',
      ],
    },

    {
      type: 'category',
      label: '001-ros-nervous-system',
      collapsed: true, // dropdown opened by default
      items: [
        'chapter-3-ros-nervous-system/part1',
        'chapter-3-ros-nervous-system/part2',
        'chapter-3-ros-nervous-system/part3',
      ],
    },

  ],

};

export default sidebars;
